language: node_js
node_js:
  - 10
install:
  - npm install
cache:
  directories: node_modules
script:
  - npx --no-install prettier --check './src/**/*.[jt]s?(x)' './.storybook/*.js?(x)'
  - npx --no-install tsc --noEmit --pretty
  - echo $branch
  - npx -p can-npm-publish@1.3.1 can-npm-publish --verbose
    branches:
      only:
        - "/^v?[0-9\\.]+/"
deploy:
  provider: npm
  email: $NPM_USER_EMAIL
  api_key: $NPM_TOKEN
  branches:
    only:
      - "/^v?[0-9\\.]+/"
