language: node_js
node_js:
  - 10
install:
  - npm install
cache:
  directories: node_modules
script:
  - npx --no-install prettier --check './src/**/*.[jt]s?(x)' './.storybook/*.js?(x)'
  - npx --no-install tsc --noEmit --pretty
deploy:
  provider: npm
  email: $NPM_USER_EMAIL
  api_key: $NPM_TOKEN
  on:
    branch: "/^v?[0-9\\.]+/"
